---
- hosts: all
  become: yes
  remote_user: serhieiev #replace with yours defined in terraform variable user

  tasks:
  - name: Ensure ntp (for time synchronization) is installed.
    apt:
      name: ntp
      state: present


  - name: Ensure ntp is running.
    service:
      name: ntp
      state: started
      enabled: yes

- hosts: web
  become: yes
  remote_user: serhieiev #replace with yours defined in terraform variable user

  tasks:
  - name: Ensure nginx is installed.
    apt:
      name: nginx
      state: present

  - name: Ensure nginx is running.
    service:
      name: nginx
      state: started
      enabled: yes

- hosts: db
  become: yes
  remote_user: serhieiev

  tasks:
  - name: Ensure mysql-client is installed.
    apt:
      name: default-mysql-client
      state: present

  - name: Ensure mysql service is running
  systemd:
    name: mysqld
    state: started
    enabled: yes
